name: lutris
confinement: strict
base: core20
grade: stable
adopt-info: lutris
compression: lzo
architectures:
  - build-on: amd64
    run-on: amd64

parts:
  enable-i386:
    plugin: nil
    override-build: |
      snapcraftctl build
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "x86_64-linux-gnu" ]; then
        dpkg --add-architecture i386
        apt update
      fi

  lutris:
    after: [enable-i386]
    plugin: python
    python-version: python3
    source: https://github.com/lutris/lutris.git
    parse-info: [share/metainfo/net.lutris.Lutris.metainfo.xml]
    override-pull: |
      snapcraftctl pull
      sed -i 's|Icon=.*|Icon=${SNAP}/share/icons/hicolor/scalable/apps/lutris.svg|' share/applications/net.lutris.Lutris.desktop
    build-packages:
      - gobject-introspection
      - libgirepository1.0-dev
      - python3
      - python3-gi
      - python3-pil
      - python3-requests
      - python3-setproctitle
      - python3-yaml
  
  lutris-runtime:
    after: [enable-i386]
    plugin: nil
    stage-packages:
      - cabextract
      - curl
      - fluid-soundfont-gs
      - gir1.2-glib-2.0
      - gir1.2-gnomedesktop-3.0
      - gir1.2-gtk-3.0
      - gir1.2-notify-0.7
      - gir1.2-webkit2-4.0
      - libgnutls30
      - libvulkan1
      - libxrandr2
      - mesa-utils
      - p7zip
      - psmisc
      - python3
      - python3-dbus
      - python3-gi
      - python3-pil
      - python3-requests
      - python3-setproctitle
      - python3-yaml
      - unzip
      - x11-xserver-utils
      - xz-utils
      - libc6-i386
    stage:
      - -lib/ld-linux.so.2
      - -usr/bin/cpp-7
      - -usr/lib/*/libjavascript*
      - -usr/lib/*/libwebkit*
      - -usr/share/doc/cpp/README.Debian
      - -usr/share/man/man1/cpp-7.1.gz


layout:
  /etc/ld.so.cache:
    bind-file: $SNAP_DATA/etc/ld.so.cache

slots:
  dbus-lutris:
    interface: dbus
    bus: session
    name: net.lutris.Lutris

plugs:
  wine-7-devel:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-7-devel-core20 


environment:
  HOME: $SNAP_USER_COMMON
  LD_LIBRARY_PATH: $SNAP/usr/lib/i386-linux-gnu:$SNAP/lib/i386-linux-gnu:$LD_LIBRARY_PATH:$LIBGL_DRIVERS_PATH
  LIBGL_DRIVERS_PATH: $LIBGL_DRIVERS_PATH:$SNAP/usr/lib/i386-linux-gnu/dri"
  LIBVA_DRIVERS_PATH: $SNAP/usr/lib/i386-linux-gnu/dri

apps:
  lutris:
    command: usr/bin/python3 $SNAP/bin/lutris -d
    extensions: [gnome-3-38]
    desktop: share/applications/net.lutris.Lutris.desktop
    common-id: net.lutris.Lutris
    plugs:
      - audio-playback
      - browser-support
      - hardware-observe
      - home
      - joystick
      - mount-observe
      - network
      - network-bind
      - network-manager
      - removable-media
      - screen-inhibit-control
      - unity7
   
