name: lutris
confinement: strict
base: core22
grade: stable
adopt-info: lutris
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
    
lint:
  # Snapcraft's `ldd` lint can't handle 32-bit things,
  # So just make it quieter and also make builds a surprising amount faster
  ignore:
    - library:
        - lib/i386-linux-gnu/**
        - usr/lib/i386-linux-gnu/**
        - lib32/**
        - usr/lib32/**
      
    
parts:
  enable-i386:
    plugin: nil
    override-build: |
      craftctl default
      if [ "$CRAFT_ARCH_TRIPLET" = "x86_64-linux-gnu" ]; then
        dpkg --add-architecture i386
        apt update
      fi

  
  lutris:
    after: [enable-i386, gamemode]
    plugin: python
    source: https://github.com/lutris/lutris.git
    parse-info: [share/metainfo/net.lutris.Lutris.metainfo.xml]
    override-pull: |
      craftctl default
      sed -i 's|Icon=.*|Icon=${SNAP}/share/icons/hicolor/scalable/apps/lutris.svg|' share/applications/net.lutris.Lutris.desktop
    build-environment:
      # WORKAROUND: The python plugin is broken with gnome extension
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    build-packages:
      - gobject-introspection
      - libgirepository1.0-dev
      - python3
      - python3-gi
      - python3-pil
      - python3-requests
      - python3-setproctitle
      - python3-yaml
    override-build: |
      craftctl default
      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/bin/lutris
    stage:
      # WORKAROUND: Skip venv from python plugin
      - -bin/activate
      - -bin/activate.csh
      - -bin/activate.fish
      - -bin/Activate.ps1
      - -bin/python
      - -bin/python3
      - -bin/python3.10
      - -bin/pip
      - -bin/pip3
      - -bin/pip3.10
      - -pyvenv.cfg
    
    
    
  gamemode:
    source: https://github.com/ashuntu/gamemode.git
    source-branch: "add-snap-support"
    plugin: meson
    organize:
      snap/lutris/current/usr: usr
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - libsystemd-dev
      - pkg-config
      - libdbus-1-dev
    prime:
      - usr/bin/gamemoderun
      - usr/lib/*/libgamemode*.so.*
  
  
  lutris-runtime:
    after: [enable-i386]
    plugin: nil
    stage-packages:
      - cabextract
      - curl
      - fluid-soundfont-gs
      - gir1.2-glib-2.0
      - gir1.2-gnomedesktop-3.0
      - gir1.2-gtk-3.0
      - gir1.2-notify-0.7
      - gir1.2-webkit2-4.0
      - libgnutls30
      - libvulkan1
      - libxrandr2
      - mesa-utils
      - p7zip
      - psmisc
      - python3.10
      - python3-dbus
      - python3-gi
      - python3-pil
      - python3-requests
      - python3-setproctitle
      - python3-yaml
      - unzip
      - x11-xserver-utils
      - xterm
      - xz-utils
      - on amd64:
          - libc6-i386
    stage:
      - -lib/ld-linux.so.2
      - -usr/bin/cpp-7
      - -usr/lib/*/libjavascript*
      - -usr/lib/*/libwebkit*
      - -usr/share/doc/cpp/README.Debian
      - -usr/share/man/man1/cpp-7.1.gz
  
  graphics-core22:
    after: [lutris]
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22 nvidia-core22
    prime:
    - bin/graphics-core22-wrapper
  
layout:
  /etc/ld.so.cache:
    bind-file: $SNAP_DATA/etc/ld.so.cache
  /usr/share/libdrm:
    bind: $SNAP/graphics/usr/share/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/graphics/usr/share/drirc.d
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/graphics/usr/share/X11/XErrorDB
  /usr/share/X11/locale:
    symlink: $SNAP/graphics/usr/share/X11/locale  
  
slots:
  lutris:
    interface: dbus
    bus: session
    name: net.lutris.Lutris

plugs:
  shmem:
    interface: shared-memory
    private: true
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22
  wine-latest:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-latest
  

environment:
  PYTHONPATH: ${SNAP}/usr/lib/python3/dist-packages:$PYTHONPATH
  LD_LIBRARY_PATH: $LIBGL_DRIVERS_PATH:$SNAP/usr/lib/i386-linux-gnu
  LIBVA_DRIVERS_PATH: $SNAP/usr/lib/i386-linux-gnu/dri
  LIBGL_DRIVERS_PATH: $SNAP/graphics/usr/lib/i386-linux-gnu/dri:$SNAP/graphics/usr/lib/x86_64-linux-gnu/dri:${LIBGL_DRIVERS_PATH:+:$LIBGL_DRIVERS_PATH}
  
apps:
  lutris:
    command-chain:
    - bin/graphics-core22-wrapper
    command: ${SNAP}/usr/bin/python3.10 ${SNAP}bin/lutris -d
    extensions: [gnome]
    desktop: share/applications/net.lutris.Lutris.desktop
    common-id: net.lutris.Lutris
    plugs:
      - home
      - audio-playback
      - network
      - network-bind
      - network-status
      - raw-usb
      - joystick
      - audio-record
      - process-control
      - bluez
      - network-control
      - shmem
      - unity7
      - removable-media
      - optical-drive
      - screen-inhibit-control
      - hardware-observe
      - mount-observe
      - system-observe
    
