name: lutris
base: core22
version: '0.5.12'
summary: Video game preservation platform.
description: |
   Lutris helps you install and play video games from all eras and from most gaming systems. 
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  
layout:
  /usr/share/libdrm:
    bind: $SNAP/graphics/usr/share/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/graphics/usr/share/drirc.d
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/graphics/usr/share/X11/XErrorDB
  /usr/share/X11/locale:
    symlink: $SNAP/graphics/usr/share/X11/locale  
  /usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
    bind: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.0

apps:
  lutris:
    command-chain:
    - bin/graphics-core22-wrapper
    command: usr/games/lutris
    extensions: [gnome]
    common-id: net.lutris.Lutris 
    desktop: usr/share/applications/net.lutris.Lutris.desktop 
    environment:
      GTK_USE_PORTAL: "1"
      HOME: $SNAP_USER_COMMON
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - home
      - audio-playback
      - network
      - network-bind
      - network-status
      - raw-usb
      - joystick
      - audio-record
      - process-control
      - bluez
      - network-control
      - shmem
      - unity7
      - removable-media
      - optical-drive
      - screen-inhibit-control
      - hardware-observe
      - mount-observe
      - system-observe
    
plugs:
  shmem:
    interface: shared-memory
    private: true
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22
  
  
slots:    
  lutris:
    interface: dbus
    bus: session
    name: net.lutris.Lutris  
  

parts:
  lutris:
    source: https://github.com/lutris/lutris/releases/download/v0.5.12/lutris_$CRAFT_PROJECT_VERSION_all.deb
    after: [gamemode]
    plugin: dump
    stage-packages:
      - fluid-soundfont-gm
      - fluid-soundfont-gs
      - python3-setproctitle
      - python3-gi
      - cabextract
      - curl
      - unzip
      - python3-magic
      - gvfs-backends
      - python3-evdev
      - p7zip
      - psmisc 
      - python3-lxml
      - python3-dbus
      - python-gi-dev
      - python3-pil
      - python3-requests
      - python3-distro
      
  
  gamemode:
    source: https://github.com/ashuntu/gamemode.git
    source-branch: "add-snap-support"
    plugin: meson
    organize:
      snap/lutris/current/usr: usr
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - libsystemd-dev
      - pkg-config
      - libdbus-1-dev
    prime:
      - usr/bin/gamemoderun
      - usr/lib/*/libgamemode*.so.*
  
  graphics-core22:
    after: [lutris]
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22 nvidia-core22
    prime:
    - bin/graphics-core22-wrapper
