name: lutris
confinement: strict
base: core20
grade: stable
adopt-info: lutris
compression: lzo
architectures:
  - build-on: amd64
    run-on: amd64

    
parts:
  enable-i386:
    plugin: nil
    override-build: |
      snapcraftctl build
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "x86_64-linux-gnu" ]; then
        dpkg --add-architecture i386
        apt update
      fi

  gnome-extension-hack:
    plugin: dump
    source: .
    override-pull: |
      snapcraftctl pull
      cat <<'EOF' > gnome-extension-hack
      #!/bin/sh
      rm -f "$XDG_DATA_HOME/icons/hicolor/"* || true
      if [ "$SNAP_ARCH" = "amd64" ]; then
        export LD_LIBRARY_PATH="$SNAP/usr/lib/i386-linux-gnu:$SNAP/lib/i386-linux-gnu:$LD_LIBRARY_PATH"

        export LIBGL_DRIVERS_PATH="$LIBGL_DRIVERS_PATH:$SNAP/usr/lib/i386-linux-gnu/dri"
        export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LIBGL_DRIVERS_PATH"
        export LIBVA_DRIVERS_PATH="$SNAP/usr/lib/i386-linux-gnu/dri"
      fi
      exec "$@"
      EOF
      chmod +x gnome-extension-hack
    organize:
      gnome-extension-hack: bin/gnome-extension-hack
  
  
  
  lutris:
    after: [enable-i386, gamemode]
    plugin: python
    source: https://github.com/lutris/lutris.git
    parse-info: [share/metainfo/net.lutris.Lutris.metainfo.xml]
    override-pull: |
      snapcraftctl pull
      sed -i 's|Icon=.*|Icon=${SNAP}/share/icons/hicolor/scalable/apps/lutris.svg|' share/applications/net.lutris.Lutris.desktop
    build-packages:
      - gobject-introspection
      - libgirepository1.0-dev
      - python3
      - python3-gi
      - python3-pil
      - python3-requests
      - python3-setproctitle
      - python3-yaml
    
  gamemode:
    source: https://github.com/ashuntu/gamemode.git
    source-branch: "add-snap-support"
    plugin: meson
    organize:
      snap/lutris/current/usr: usr
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - libsystemd-dev
      - pkg-config
      - libdbus-1-dev
    prime:
      - usr/bin/gamemoderun
      - usr/lib/*/libgamemode*.so.*
  
  
  lutris-runtime:
    after: [enable-i386]
    plugin: nil
    stage-packages:
      - cabextract
      - curl
      - fluid-soundfont-gs
      - gir1.2-glib-2.0
      - gir1.2-gnomedesktop-3.0
      - gir1.2-gtk-3.0
      - gir1.2-notify-0.7
      - gir1.2-webkit2-4.0
      - libgnutls30
      - libvulkan1
      - libxrandr2
      - p7zip
      - psmisc
      - python3-dbus
      - python3-gi
      - python3-pil
      - python3-requests
      - python3-setproctitle
      - python3-yaml
      - unzip
      - x11-xserver-utils
      - xz-utils
      - on amd64:
          - libc6-i386
    stage:
      - -lib/ld-linux.so.2
      - -usr/bin/cpp-7
      - -usr/lib/*/libjavascript*
      - -usr/lib/*/libwebkit*
      - -usr/share/doc/cpp/README.Debian
      - -usr/share/man/man1/cpp-7.1.gz
  
hooks:
  install:
    command-chain:
    - bin/gnome-extension-hack
  
  post-refresh:
    command-chain:
    - bin/gnome-extension-hack

slots:
  lutris:
    interface: dbus
    bus: session
    name: net.lutris.Lutris

plugs:
  shmem:
    interface: shared-memory
    private: true
  
  
apps:
  lutris:
    command: bin/gnome-extension-hack $SNAP/bin/lutris -d   
    extensions: [gnome-3-38]
    desktop: share/applications/net.lutris.Lutris.desktop
    common-id: net.lutris.Lutris
    plugs:
      - home
      - audio-playback
      - network
      - network-bind
      - network-status
      - raw-usb
      - joystick
      - audio-record
      - process-control
      - bluez
      - network-control
      - shmem
      - unity7
      - removable-media
      - optical-drive
      - screen-inhibit-control
      - hardware-observe
      - mount-observe
      - system-observe
    
