name: lutris
base: core22
adopt-info: lutris
grade: devel
confinement: devmode
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
assumes:
  - snapd2.59
  
package-repositories:
  - type: apt
    architectures: [i386,amd64]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    key-server: keyserver.ubuntu.com
    formats: [deb]
    components: [main, multiverse, universe, restricted]
    suites: [jammy]
    url: https://archive.ubuntu.com/ubuntu

lint:
  ignore:
    - library:
        - lib/i386-linux-gnu/**
        - usr/lib/i386-linux-gnu/**
        - lib32/**
        - usr/lib32/**
 
layout:
  /usr/share/libdrm:
    bind: $SNAP/graphics/usr/share/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/graphics/usr/share/drirc.d
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/graphics/usr/share/X11/XErrorDB
  /usr/share/X11/locale:
    symlink: $SNAP/graphics/usr/share/X11/locale   

apps: 
  lutris:
    command-chain:
    - bin/graphics-core22-wrapper
    command: usr/bin/lutris
    extensions: [gnome]
    environment:
      PYTHONPATH: ${SNAP}/usr/lib/python3/dist-packages:$PYTHONPATH
      HOME: $SNAP_USER_COMMON
      TMPDIR: $XDG_RUNTIME_DIR
      APPIMAGE_EXTRACT_AND_RUN: 1
    common-id: net.lutris.Lutris 
    desktop: usr/share/applications/net.lutris.Lutris.desktop 
    plugs:
      - home
      - shmem
      - audio-playback
      - network
      - network-bind
      - network-status
      - joystick
      - audio-record
      - process-control
      - bluez
      - browser-support
      - unity7
      - removable-media
      - optical-drive
      - screen-inhibit-control
      - hardware-observe
      - mount-observe
      - system-observe
      - fuse-support
      - physical-memory-observe
      - upower-observe
      - raw-usb
      
plugs:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22
  shmem:
    interface: shared-memory
    private: true

slots:    
  lutris:
    interface: dbus
    bus: session
    name: net.lutris.Lutris  
  

parts:
  lutris:
    source: https://github.com/lutris/lutris.git
    after: [lutris-runtime]
    plugin: meson
    parse-info: [usr/share/metainfo/net.lutris.Lutris.metainfo.xml]
    meson-parameters:
      - --prefix=/snap/lutris/current/usr
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
    override-build: |
      craftctl default
      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/lutris/current/usr/bin/lutris
    organize:
      snap/lutris/current/usr: usr 
  
  lutris-runtime:
    plugin: nil
    stage-packages:
      - cabextract
      - curl
      - fluid-soundfont-gs
      - gir1.2-glib-2.0
      - gir1.2-gtk-3.0
      - gir1.2-notify-0.7
      - gir1.2-webkit2-4.1
      - libgirepository-1.0-1 
      - p7zip
      - psmisc
      - python3-dbus
      - python3-gi
      - python3-pil
      - python3-requests
      - python3-setproctitle
      - python3-yaml
      - python3-distro
      - python3-cairo
      - python3-lxml
      - python3-evdev
      - python3-magic
      - unzip
      - xterm
      - pciutils
      - xz-utils
      - x11-xserver-utils
      - libc6-i386
      - libgnutls30
      - mesa-utils
      - vulkan-tools
      - gettext
      - libvulkan1
      - on amd64:
        - libgnutls30:i386
        - libasound2-plugins:i386
        - libsdl2-2.0-0:i386
        - libdbus-1-3:i386
        - libsqlite3-0:i386
        - libx11-6:i386
        - libglvnd0:i386
    stage:
      - -lib/ld-linux.so.2
      - -usr/bin/cpp-7
      - -usr/lib/*/libjavascript*
      - -usr/lib/*/libwebkit*
      - -usr/share/doc/cpp/README.Debian
      - -usr/share/man/man1/cpp-7.1.gz
  
  gamemode:
    source: https://github.com/ashuntu/gamemode.git
    source-branch: "add-snap-support"
    plugin: meson
    organize:
      snap/lutris/current/usr: usr
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - libsystemd-dev
      - pkg-config
      - libdbus-1-dev
    prime:
      - usr/bin/gamemoderun
      - usr/lib/*/libgamemode*.so.*
   
  graphics-core22:
    after: [lutris]
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22 nvidia-core22
    prime:
    - bin/graphics-core22-wrapper
